<?php
/**
 * this creates the visual exception page when something goes wrong in the system
 * 
 * @package System
 * @subpackage System_Exception
 * @author Mark Henderson
 * @param Exception $e
 */
$e = $this->get('e');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>System Exception</title>
	
</head>
<body>
    <h1>Caught exception: <?php echo $e->getMessage(); ?></h1>
    <h2>File: <?php echo $e->getFile()?></h2>
    <h2>Line: <?php echo $e->getLine()?></h2>
    <h3>Trace</h3>
    <pre>
    <?php print_r($e->getTraceAsString()); ?>
    </pre>
    <h3>Exception Object</h3>
    <pre>
    <?php print_r($e); ?>
    </pre>
    <h3>Debug Backtrace</h3>
    <pre>
    <?php debug_print_backtrace (); ?>
    </pre>
</body>
</html>
